services:
#    payment.example:
#        class: PaymentBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

parameters:
    enum_months:
        - January
        - February
        - March
        - April
        - May
        - June
        - July
        - August
        - September
        - October
        - November
        - December
    
    enum_days:
        - 31
        - 28
        - 31
        - 30
        - 31
        - 30
        - 31
        - 31
        - 30
        - 31
        - 30
        - 31
